anchor_job_defaults: &job_defaults
    working_directory: ~/gitlab-release
    docker:
        - image: ptsecurity/node-container:0.0.4

anchor_post_checkout: &post_checkout
    post: git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"

version: 2
jobs:
    build:
        <<: *job_defaults
        steps:
            - checkout:
                  <<: *post_checkout
            - restore_cache:
                  key: gitlab-release-{{ checksum "package.json" }}
            - run:
                  name: System information
                  command: |
                      echo "Node.js $(node -v)"
                      echo "npm $(npm -v)"
                      echo "Yarn v$(yarn --version)"
            - run:
                  name: Install npm packages
                  command: npm install
            - save_cache:
                  key: gitlab-release-{{ checksum "package.json" }}
                  paths:
                    - "node_modules"
            - run:
                  name: Unit Test
                  command: npm run test:unit
            - persist_to_workspace:
                  root: ./
                  paths:
                      - lib/
                      - CHANGELOG.md
                      - cli.js
                      - index.js
                      - LICENSE
                      - package.json
                      - README.md

    publish:
        <<: *job_defaults
        steps:
            - attach_workspace:
                  at: ./
            - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            - run: npm publish --access public

workflows:
    version: 2
    default_workflow:
        jobs:
            - build:
                  filters:
                      tags:
                          only: /.*/
            - publish:
                  requires:
                        - build
                  filters:
                      branches:
                          ignore: /.*/
                      tags:
                          only: /^\d+\.\d+\.\d+$/
